{
 "title": "CPU",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "funcCalls",
    "label": "FuncCalls",
    "query": "screeps.pandamaster.funcCalls.*"
   },
   {
    "name": "intentCalls",
    "label": "IntentCalls",
    "query": "screeps.pandamaster.intentCalls.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Stat collecting time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.ticksStatsCollecting)"
    }
   ]
  },
  { "title": "Intents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Intent call count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.pandamaster.intentCalls.$intentCalls.callCount, 3)"
    }
   ]
  },
  {
   "title": "Intent cpu used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.pandamaster.intentCalls.$intentCalls.cpuUsed, 3)"
    }
   ]
  },
  { "title": "Functions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Function call count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.pandamaster.funcCalls.$funcCalls.callCount, 3)"
    }
   ]
  },
  {
   "title": "Function cpu used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.pandamaster.funcCalls.$funcCalls.cpuUsed, 3)"
    }
   ]
  }
 ]
}