{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Stat collecting time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.pandamaster.ticksStatsCollecting"
    }
   ]
  },
  { "title": "Global Cpu Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Bucket Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.cpu.bucket.*)"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.cpu.usage.*)"
    }
   ]
  },
  { "title": "GCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GCL level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.gcl.level)"
    }
   ]
  },
  {
   "title": "GCL progress",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "divideSeries(screeps.pandamaster.gcl.progress, #A)",
     "targetFull": "divideSeries(screeps.pandamaster.gcl.progress, screeps.pandamaster.gcl.progressTotal)"
    }
   ]
  },
  {
   "title": "GCL prediction",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByMetric(holtWintersForecast(divideSeries(#B, #A)))",
     "targetFull": "aliasByMetric(holtWintersForecast(divideSeries(divideSeries(screeps.pandamaster.gcl.progressTotal, screeps.pandamaster.gcl.progress), perSecond(movingAverage(screeps.pandamaster.gcl.progress, '5hour')))))"
    }
   ]
  },
  { "title": "Cashflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Income",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.*.energyIncome.*)"
    }
   ]
  },
  {
   "title": "Net energy profit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.*.energyIncome.*, 4, 'sum'), #B, #C), 'Net profit')",
     "targetFull": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.*.energyIncome.*, 4, 'sum'), groupByNode(screeps.pandamaster.rooms.*.energyExpenses.*.*, 4, 'sum'), groupByNode(screeps.pandamaster.rooms.*.energyExpenses.*, 4, 'sum')), 'Net profit')"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.*.energyExpenses.*)"
    },
    {
     "target": "aliasByNode(groupByNode(screeps.pandamaster.rooms.*.energyExpenses.*.*, 5, 'sum'), 0)"
    }
   ]
  },
  {
   "title": "Spawn costs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.pandamaster.rooms.*.energyExpenses.*.*, 6)"
    }
   ]
  },
  { "title": "RCL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "RCL levels",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.pandamaster.rooms.*.rcl.level, 3)"
    }
   ]
  },
  {
   "title": "RCL levels",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(asPercent(screeps.pandamaster.rooms.*.rcl.progress, #A), 3)",
     "targetFull": "aliasByNode(asPercent(screeps.pandamaster.rooms.*.rcl.progress, aliasByMetric(screeps.pandamaster.rooms.*.rcl.progressTotal)), 3)"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Active Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(groupByNode(screeps.pandamaster.rooms.*.activeJobs.*, 5, 'sum'))"
    }
   ]
  },
  {
   "title": "Creep Count Per Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(groupByNode(screeps.pandamaster.rooms.*.creepCountPerJob.*, 5, 'sum'))"
    }
   ]
  },
  {
   "title": "Object counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Creep counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(screeps.pandamaster.rooms.*.creepCount, 3)"
      }
     ]
    },
    {
     "title": "Structure counts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(screeps.pandamaster.rooms.*.structureCount, 3)"
      }
     ]
    }
   ]
  }
 ]
}