{
 "title": "Rooms",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "rooms", "label": "Rooms", "query": "screeps.pandamaster.rooms.*" }
  ]
 },
 "panels": [
  {
   "title": "Stat collecting time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.pandamaster.ticksStatsCollecting"
    }
   ]
  },
  { "title": "${rooms}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "rooms" },
  {
   "title": "Creep count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.creepCount)"
    }
   ]
  },
  {
   "title": "Structure count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.structureCount)"
    }
   ]
  },
  {
   "title": "Energy income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyIncome.*)"
    }
   ]
  },
  {
   "title": "Energy net profit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.$rooms.energyIncome.*, 4, 'sum'), #A, #B), 'Net profit')",
     "targetFull": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.$rooms.energyIncome.*, 4, 'sum'), aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.*), aliasByMetric(groupByNode(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*, 5, 'sum'))), 'Net profit')"
    }
   ]
  },
  {
   "title": "Energy expenses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.*)"
    },
    {
     "target": "aliasByMetric(groupByNode(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*, 5, 'sum'))"
    }
   ]
  },
  {
   "title": "Spawn energy costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*)"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.activeJobs.*)"
    }
   ]
  },
  {
   "title": "Creep count per job type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.creepCountPerJob.*)"
    }
   ]
  },
  {
   "title": "Energy In storages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyInStorages.*)"
    }
   ]
  },
  { "title": "${rooms}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Creep count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.creepCount)"
    }
   ]
  },
  {
   "title": "Structure count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.structureCount)"
    }
   ]
  },
  {
   "title": "Energy income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyIncome.*)"
    }
   ]
  },
  {
   "title": "Energy net profit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.$rooms.energyIncome.*, 4, 'sum'), #A, #B), 'Net profit')",
     "targetFull": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.$rooms.energyIncome.*, 4, 'sum'), aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.*), aliasByMetric(groupByNode(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*, 5, 'sum'))), 'Net profit')"
    }
   ]
  },
  {
   "title": "Energy expenses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.*)"
    },
    {
     "target": "aliasByMetric(groupByNode(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*, 5, 'sum'))"
    }
   ]
  },
  {
   "title": "Spawn energy costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*)"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.activeJobs.*)"
    }
   ]
  },
  {
   "title": "Creep count per job type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.creepCountPerJob.*)"
    }
   ]
  },
  {
   "title": "Energy In storages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyInStorages.*)"
    }
   ]
  },
  { "title": "${rooms}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Creep count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.creepCount)"
    }
   ]
  },
  {
   "title": "Structure count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.structureCount)"
    }
   ]
  },
  {
   "title": "Energy income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyIncome.*)"
    }
   ]
  },
  {
   "title": "Energy net profit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.$rooms.energyIncome.*, 4, 'sum'), #A, #B), 'Net profit')",
     "targetFull": "alias(diffSeries(groupByNode(screeps.pandamaster.rooms.$rooms.energyIncome.*, 4, 'sum'), aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.*), aliasByMetric(groupByNode(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*, 5, 'sum'))), 'Net profit')"
    }
   ]
  },
  {
   "title": "Energy expenses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.*)"
    },
    {
     "target": "aliasByMetric(groupByNode(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*, 5, 'sum'))"
    }
   ]
  },
  {
   "title": "Spawn energy costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyExpenses.spawn.*)"
    }
   ]
  },
  {
   "title": "Active jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.activeJobs.*)"
    }
   ]
  },
  {
   "title": "Creep count per job type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.creepCountPerJob.*)"
    }
   ]
  },
  {
   "title": "Energy In storages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(screeps.pandamaster.rooms.$rooms.energyInStorages.*)"
    }
   ]
  }
 ]
}